# Generated by Django 4.2.7 on 2023-11-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_usuario_cedula_usuario_direccion_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='img/default_user_image1.png', upload_to='photos'),
        ),
    ]
