# Generated by Django 4.2.7 on 2023-12-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos_institucionales', '0007_alter_curso_carrera_delete_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='horaEntrada',
            field=models.TimeField(blank=True, help_text='Hora de inicio del curso', null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='horaSalida',
            field=models.TimeField(blank=True, help_text='Hora de salida del curso', null=True),
        ),
    ]
